### PR TITLE
Basic Modal Feature

### LINKED ISSUE #529: Build modal
### User Story

As a developer, I want a modular modal component, so I can easily display auxiliary content on a web page.

### Description

This modal should be a generic container for content. We need this to be built in the UI library using React and TailwindCSS.

### Acceptance Criteria

- [ ] Build the modal component in the`ui` package

### Design References

- N/A

### Technical References

- [TailwindCSS Docs](https://tailwindcss.com/)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gibsonliketheguitar**
### Description

Implement Modal Feature with [Radix Dialog API](https://www.radix-ui.com/docs/primitives/components/dialog)

### Related Issues

Resolves #529 
### Testing

```
 PASS  packages/website/src/widgets/header/header.test.tsx
 PASS  packages/ui/src/components/modal/modal.test.tsx
   
Test Suites: 2 passed, 2 total
Tests:       11 passed, 11 total
Snapshots:   0 total
Time:        15.76 s
Ran all test suites.
✨  Done in 17.03s.
```
File                                           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------------------------------|---------|----------|---------|---------|-------------------
ui/src/components/modal                                  |   56.25 |      100 |      50 |   56.25 |                   
  modal.stories.tsx                                       |       0 |      100 |       0 |       0 | 2-35           
modal.tsx                                               |     100 |      100 |     100 |     100 |      

### Checklist

- [x] I have followed all conventions outlined in our documentation.
- [x] I have fully tested my changes and confirmed that all new and existing tests pass.
- [x] I have written meaningful commit messages for all changes.
- [x] I have linted and formatted my changes to follow the code style of this repository.
- [ ] I have updated our documentation, accordingly.
- [x] I have checked currently opened pull requests to ensure that there are no pending pull request for the same changes or issues.
- [x] I have confirmed that this pull request fully meets the acceptance criteria for all related issues listed above.

### CODE REVIEW

**Comment by gibsonliketheguitar** [comment]
Once this PR. I think we should squash commits?

**Comment by glenflorendo** [comment]
> Once this PR. I think we should squash commits?

What do you mean "once this PR"?

**Comment by gibsonliketheguitar** [comment]
My bad, had a brain fart. I meant to say, "Once this PR is finished/ready"

**Comment by glenflorendo** [comment]
> My bad, had a brain fart. I meant to say, "Once this PR is finished/ready"

Commits can be squashed before being merged. I think that's better, so we don't rewrite the history on our `main` branch.

**Pull request merged**
